name: hll_gun_calculator
description: hll-gun-calculator
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dio: ^5.0.0
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  dio_cookie_manager: ^2.0.0
  file_picker: ^6.2.0
  dartfx: ^1.0.13
  provider: ^6.0.2
  shared_preferences: ^2.0.6
  animations: ^2.0.7
  flutter_custom_license_page: ^0.0.3
  fluro: ^2.0.3
  url_launcher: ^6.1.10
  package_info_plus: ^4.1.0
  fluttertoast: ^8.2.4
  audioplayers: ^5.2.1
  flutter_translate: ^4.0.3
  flutter_i18n: ^0.34.0
  flex_color_scheme: ^7.3.1
  json_annotation: ^4.8.1
  flutter_map: ^5.0.0
  extended_image: ^8.2.0
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.10+1

  # REQUIRED!
  build_runner: ^2.3.3

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^3.0.0

  # Not required to use `json_serializable`.
  dart_flutter_team_lints: ^2.0.0

  # REQUIRED!
  json_serializable: ^6.6.0

  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/maps/
    - assets/images/icon/
    - assets/images/factions/
    - assets/splash/
    - assets/json/
    - assets/lang/
    - assets/audio/