name: Build and Deploy
on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'

      - name: Build Web
        run: flutter build web

      - name: Checkout Pages Repo
        uses: actions/checkout@v2
        with:
          repository: hll-gun-calculator/hll-gun-calculato-app-for-web
          token: ${{ secrets.PUSH_TOKEN }}
          path: .deploy

      - name: Deploy to GitHub Pages
        run: |
          cp -r build/web/* .deploy
          cd .deploy
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
